/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ItemType = IDL.Variant({
  'jewelry' : IDL.Null,
  'artwork' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Artwork = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Jewelry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'type' : IDL.Text,
  'weightGram' : IDL.Nat,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
  'material' : IDL.Text,
});
export const PurchaseOrder = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Text,
  'handled' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactMessageInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArtwork' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'createJewelry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, ItemType, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteArtwork' : IDL.Func([IDL.Text], [], []),
  'deleteJewelry' : IDL.Func([IDL.Text], [], []),
  'getAboutContent' : IDL.Func([], [IDL.Text], ['query']),
  'getAllArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllJewelry' : IDL.Func([], [IDL.Vec(Jewelry)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getArtwork' : IDL.Func([IDL.Text], [Artwork], ['query']),
  'getAvailableArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'getAvailableJewelry' : IDL.Func([], [IDL.Vec(Jewelry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJewelry' : IDL.Func([IDL.Text], [Jewelry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderHandled' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendContactMessage' : IDL.Func([ContactMessageInput], [IDL.Nat], []),
  'setArtworkImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'setJewelryImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'updateArtwork' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateJewelry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ItemType = IDL.Variant({ 'jewelry' : IDL.Null, 'artwork' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Artwork = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Jewelry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'type' : IDL.Text,
    'weightGram' : IDL.Nat,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
    'material' : IDL.Text,
  });
  const PurchaseOrder = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Text,
    'handled' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactMessageInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArtwork' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'createJewelry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, ItemType, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteArtwork' : IDL.Func([IDL.Text], [], []),
    'deleteJewelry' : IDL.Func([IDL.Text], [], []),
    'getAboutContent' : IDL.Func([], [IDL.Text], ['query']),
    'getAllArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllJewelry' : IDL.Func([], [IDL.Vec(Jewelry)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getArtwork' : IDL.Func([IDL.Text], [Artwork], ['query']),
    'getAvailableArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'getAvailableJewelry' : IDL.Func([], [IDL.Vec(Jewelry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJewelry' : IDL.Func([IDL.Text], [Jewelry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderHandled' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendContactMessage' : IDL.Func([ContactMessageInput], [IDL.Nat], []),
    'setArtworkImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'setJewelryImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'updateArtwork' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateJewelry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };