/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artwork {
  'id' : string,
  'title' : string,
  'description' : string,
  'available' : boolean,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactMessageInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export type ItemType = { 'jewelry' : null } |
  { 'artwork' : null };
export interface Jewelry {
  'id' : string,
  'name' : string,
  'type' : string,
  'weightGram' : bigint,
  'description' : string,
  'available' : boolean,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
  'material' : string,
}
export interface PurchaseOrder {
  'id' : bigint,
  'itemId' : string,
  'handled' : boolean,
  'name' : string,
  'email' : string,
  'message' : [] | [string],
  'itemType' : ItemType,
  'quantity' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArtwork' : ActorMethod<[string, string, bigint], string>,
  'createJewelry' : ActorMethod<
    [string, string, bigint, string, bigint, string],
    string
  >,
  'createOrder' : ActorMethod<
    [string, ItemType, string, string, [] | [string], bigint],
    bigint
  >,
  'deleteArtwork' : ActorMethod<[string], undefined>,
  'deleteJewelry' : ActorMethod<[string], undefined>,
  'getAboutContent' : ActorMethod<[], string>,
  'getAllArtworks' : ActorMethod<[], Array<Artwork>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllJewelry' : ActorMethod<[], Array<Jewelry>>,
  'getAllOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getArtwork' : ActorMethod<[string], Artwork>,
  'getAvailableArtworks' : ActorMethod<[], Array<Artwork>>,
  'getAvailableJewelry' : ActorMethod<[], Array<Jewelry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJewelry' : ActorMethod<[string], Jewelry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderHandled' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendContactMessage' : ActorMethod<[ContactMessageInput], bigint>,
  'setArtworkImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'setJewelryImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'updateArtwork' : ActorMethod<
    [string, string, string, bigint, boolean],
    undefined
  >,
  'updateJewelry' : ActorMethod<
    [string, string, string, bigint, boolean, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];